---
# Practicalli Engineering Playbook
site_name: Practicalli Engineering Playbook
site_url: https://practical.li/engineering-playbook
site_description: Practical guides to common Engineering tasks
site_author: Practicalli
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/engineering-playbook/
edit_uri: https://github.com/practicalli/engineering-playbook/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes # Nav sections can have files
    - navigation.instant # Avoid page reloading for internal links
    - navigation.top
    - navigation.tracking # Update URL with anchor
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji ""
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized:
      # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [ MKDOCS_SOCIAL_CARDS_GENERATE, true ]
  # Redirect pages when moved or changed
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  #       reference/meta-tags.md: reference/index.md

  # Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-SMJSV1S03Y
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Overview:
      - index.md
      - Contributing: introduction/contributing.md
      - Writing Tips: introduction/writing-tips.md
  - Architecture:
      - architecture/index.md
      - Structurizr: architecture/structurizr.md
  - Build tool:
      - build-tool/index.md
      - build-tool/make.md
      - build-tool/babashka-task-runner.md
  - Code Quality:
      - code-quality/index.md
      - code-quality/megalinter.md
      - code-quality/clojure.md
  - Command Line:
      - command-line/index.md
      - Kitty Terminal: command-line/kitty-terminal.md
  - Continuous Integration:
      - continuous-integration/index.md
      - Docker:
          - continuous-integration/docker/index.md
          - Install: continuous-integration/docker/install.md
          - Desktop: continuous-integration/docker/desktop.md
          - Desktop Extensions: continuous-integration/docker/desktop-extensions.md
          - Images: continuous-integration/docker/images.md
          - Dockerfile Design: continuous-integration/docker/dockerfile.md
          - Clojure Multi-stage Dockerfile: continuous-integration/docker/clojure-multi-stage-dockerfile.md
          - Compose: continuous-integration/docker/compose.md
      - GitHub:
          - continuous-integration/github/index.md
          - Actions: continuous-integration/github/actions.md
          - Common jobs: continuous-integration/github/common-jobs.md
          - Trigger Events: continuous-integration/github/trigger-events.md
          - Workflows:
              - continuous-integration/github/workflows/index.md
              - continuous-integration/github/workflows/megalinter.md
              - continuous-integration/github/workflows/luarocks.md
  - Documentation:
      - technical-writing/index.md
      # - technical-writing/techniques.md
      # - technical-writing/site-generator/mkdocs.md
      # - Version Control:
      #     - version-control/index.md
      #     - version-control/git-client-configuration.md
  - Practices:
      - practices/index.md
      - practices/behaviour-driven-development.md
      # - TODO: practices/root-cause-analysis.md
      # - TODO: practices/five-whys.md
      # - TODO: practices/thinking-hats.md
      - practices/deliberate-practice.md
      # - TODO: practices/code-kata.md
  - Operating Systems:
      - os/index.md
      - Linux:
          - os/linux/index.md
          - os/debian.md
          - os/ubuntu.md
          - Regolith: os/linux/regolith.md
      - Shell:
          - os/shell/index.md
          - os/shell/bash.md
          - os/shell/zsh.md
          - os/shell/fish.md
