---
# Practicalli Engineering Playbook
site_name: Practicalli Engineering Playbook
site_url: https://practical.li/engineering-playbook
site_description: Practical guides to common Engineering tasks
site_author: Practicalli
site_org: https://practical.li
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/engineering-playbook/
edit_uri: https://github.com/practicalli/engineering-playbook/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes # Nav sections can have files
    - navigation.instant # Avoid page reloading for internal links
    - navigation.top
    - navigation.tracking # Update URL with sub-heading anchor names
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized:
      # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [ MKDOCS_SOCIAL_CARDS_GENERATE, true ]
  # Redirect pages when moved or changed
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  #       reference/meta-tags.md: reference/index.md

  # Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-SMJSV1S03Y
  social:
    - icon: material/web
      link: https://practical.li/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Overview:
      - index.md
      - Contributing: introduction/contributing.md
      - Writing Tips: introduction/writing-tips.md
  - Build tool:
      - build-tool/index.md
      - build-tool/make.md
      - build-tool/babashka-task-runner.md
  - Careers:
      - careers/index.md
      - careers/engineer.md
      - careers/engineering-manager.md
  - Change Management:
      - change-management/index.md
  - Code Quality:
      - code-quality/index.md
      - code-quality/megalinter.md
      - code-quality/clojure.md
  - Continuous Integration:
      - continuous-integration/index.md
      - Docker:
          - continuous-integration/docker/index.md
          - Install: continuous-integration/docker/install.md
          - Desktop:
              - continuous-integration/docker/desktop/index.md
              - Desktop Extensions: continuous-integration/docker/desktop/extensions.md
          - Images: continuous-integration/docker/images.md
          - Dockerfile Design: continuous-integration/docker/dockerfile.md
          - Clojure Multi-stage Dockerfile: continuous-integration/docker/clojure-multi-stage-dockerfile.md
          - Compose: continuous-integration/docker/compose.md
      - GitHub:
          - continuous-integration/github/index.md
          - Actions: continuous-integration/github/actions.md
          - Common jobs: continuous-integration/github/common-jobs.md
          - Trigger Events: continuous-integration/github/trigger-events.md
          - Workflows:
              - continuous-integration/github/workflows/index.md
              - continuous-integration/github/workflows/megalinter.md
              - continuous-integration/github/workflows/luarocks.md
              - continuous-integration/github/workflows/practicalli.md
              - continuous-integration/github/workflows/system-catalog.md
  - Culture:
      - culture/index.md
      - culture/anti-patterns.md
      - culture/burnout.md
      - culture/documentation.md
      - culture/leadership.md
  - Documentation:
      - technical-writing/index.md
      - technical-writing/techniques.md
      - Static Sites:
          - technical-writing/static-site/index.md
          - MkDocs: technical-writing/static-site/mkdocs.md
  - Operating Systems:
      - os/index.md
      - Command Line:
          - os/command-line/index.md
          - Kitty Terminal: os/command-line/kitty-terminal.md
          - Warp Terminal: os/command-line/warp.md
          - Shell:
              - os/command-line/shell/index.md
              - Bash: os/command-line/shell/bash.md
              - Zsh: os/command-line/shell/zsh.md
              - Fish: os/command-line/shell/fish.md
              - Starship prompt: os/command-line/shell/starship-prompt.md
          - Commands:
              - os/command-line/commands/index.md
              - File system: os/command-line/commands/file-system.md
              - Accounts & permissions: os/command-line/commands/accounts-permissions.md
              - Scheduled tasks: os/command-line/commands/cron.md
      - Linux:
          - Overview: os/linux/index.md
          - Debian:
              - os/debian-linux/index.md
              - Install: os/debian-linux/install.md
              - Post Install: os/debian-linux/post-install.md
          - Ubuntu: os/ubuntu-linux.md
          - Hyprland: os/linux/hyprland.md
          - Regolith: os/linux/regolith.md
      - MacOSX: os/macosx.md
  - Persistence:
      - persistence/index.md
      - RDBMS:
          - Overview: persistence/rdbms/index.md
          - Client:
              - persistence/rdbms/client/index.md
              - Command Line: persistence/rdbms/client/cli.md
              - DBeaver: persistence/rdbms/client/dbeaver.md
              - Postgres Admin: persistence/rdbms/client/pgadmin.md
          - Server:
              - persistence/rdbms/server/h2.md
              - persistence/rdbms/server/mariadb.md
              - PostgreSQL:
                  - Overview: persistence/rdbms/server/postgresql/index.md
          - SQL:
              - Overview: persistence/rdbms/sql/index.md
              - Examples: persistence/rdbms/sql/examples.md
  - Practices:
      - practices/index.md
      - Discussions:
          - practices/discussions/index.md
          - Asking Questions: practices/discussions/asking-questions.md
          - practices/discussions/rolling-wave-planning.md
          - practices/discussions/one-to-one-meeting.md
          - Retrospective: practices/discussions/retrospective.md
          - Standup: practices/discussions/standup.md
          - Five Whys: practices/discussions/five-whys.md
          - Thinking Hats: practices/discussions/thinking-hats.md
      - Kanban:
          - practices/kanban/index.md
          - Value-Stream Mapping: practices/kanban/value-stream-mapping.md
      - BDD:
          - practices/behaviour-driven-development/index.md
      - Tech Debt: practices/technical-debt.md
      - Root Cause Analysis: practices/root-cause-analysis.md
      - Deliberate Practice:
          - practices/deliberate-practice/index.md
          - Architecture Kata: practices/deliberate-practice/architecture-kata.md
          - Code Kata: practices/deliberate-practice/code-kata.md
      - practices/test-driven-development.md
      - practices/managing-bias.md

  - Programming Languages:
      - programming-languages/index.md
      - JavaScript:
          - programming-languages/javascript/index.md
          - programming-languages/javascript/nodejs.md
  - Source Control:
      - source-control/index.md
      # - source-control/git-overview.md
      - source-control/git-configuration.md
      - source-control/git-concepts.md
      - source-control/git-status.md
  - Software Design:
      - software-design/index.md
      - Anti-patterns: software-design/anti-patterns/index.md
      - Architecture:
          - software-design/architecture/index.md
          - Structurizr: software-design/architecture/structurizr.md
          - Architecture Design Record: software-design/architecture/adr.md
      - Design Patterns:
          - software-design/design-patterns/index.md
          - software-design/design-patterns/command-query-separation.md
          - software-design/design-patterns/cqrs.md
